# Generated by Django 5.1.3 on 2024-11-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localite', '0003_alter_customerregistrationmodel_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerregistrationmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='customerregistrationmodel',
            name='customer_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
