# Generated by Django 5.1.3 on 2024-11-27 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localite', '0005_alter_customerregistrationmodel_customer_id'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_bag_items',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('product_photo', models.ImageField(upload_to='photos/')),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Localite.customerregistrationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='customer_whislist_items',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('product_photo', models.ImageField(upload_to='photos/')),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Localite.customerregistrationmodel')),
            ],
        ),
    ]
