# Generated by Django 5.1.3 on 2024-11-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_clothesproducts_seller_drinksproducts_seller_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothesproducts',
            old_name='image',
            new_name='product_photo',
        ),
        migrations.RenameField(
            model_name='icecreamproducts',
            old_name='image',
            new_name='product_photo',
        ),
        migrations.RenameField(
            model_name='meatproducts',
            old_name='image',
            new_name='product_photo',
        ),
        migrations.RenameField(
            model_name='vegetablesproducts',
            old_name='image',
            new_name='product_photo',
        ),
    ]
