# Generated by Django 5.1.3 on 2024-11-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_image_clothesproducts_product_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meatproducts',
            name='product_name',
        ),
    ]
