# Generated by Django 5.1.3 on 2024-11-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesShopSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_type', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('opening_hours', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop_Image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='DrinksShopSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_type', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('opening_hours', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop_Image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicsShopSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_type', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('opening_hours', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop_Image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='FoodsShopSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_type', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('opening_hours', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop_Image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='FruitsShopSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_type', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('opening_hours', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop_Image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='GroceryShopSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_type', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('opening_hours', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop_Image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='HouseComponentShopSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_type', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('opening_hours', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop_Image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='IceCreamShopSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_type', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('opening_hours', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop_Image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='MeatShopSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_type', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('opening_hours', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop_Image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='VegetablesShopSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_type', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('opening_hours', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop_Image', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
