# Generated by Django 5.1.3 on 2024-11-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localite', '0002_alter_customerregistrationmodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerregistrationmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customerregistrationmodel',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
