# Generated by Django 5.1.3 on 2024-11-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localite', '0004_remove_customerregistrationmodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerregistrationmodel',
            name='customer_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
