# Generated by Django 5.1.3 on 2024-11-18 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='clothing_images/')),
                ('delivery', models.CharField(choices=[('Yes', 'yes'), ('No', 'No')], default='Yes', max_length=4)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.clothesshopseller')),
            ],
        ),
        migrations.CreateModel(
            name='DrinksProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ingredients', models.CharField(max_length=50)),
                ('drink_Type', models.CharField(choices=[('A', 'Alcoholic'), ('N-A', 'Non-Alcoholic')], default='N-A', max_length=3)),
                ('variety', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('product_photo', models.ImageField(upload_to='photos/')),
                ('delivery', models.CharField(choices=[('Yes', 'yes'), ('No', 'No')], default='Yes', max_length=4)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.drinksshopseller')),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicsProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('brand', models.CharField(max_length=50)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('battery_life', models.CharField(blank=True, max_length=50, null=True)),
                ('display_type', models.CharField(blank=True, max_length=50, null=True)),
                ('storage', models.CharField(blank=True, max_length=100, null=True)),
                ('processor', models.CharField(blank=True, max_length=100, null=True)),
                ('memory', models.CharField(blank=True, max_length=50, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True)),
                ('Warrenty', models.CharField(choices=[('y', 'yes'), ('N', 'No')], default='N', max_length=2)),
                ('product_photo', models.ImageField(upload_to='photos/')),
                ('delivery', models.CharField(choices=[('Yes', 'yes'), ('No', 'No')], default='Yes', max_length=4)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.electronicsshopseller')),
            ],
        ),
        migrations.CreateModel(
            name='FoodsProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Nutrations', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('packaging', models.CharField(choices=[('Bg', 'Bag'), ('J', 'Jar'), ('B', 'Box'), ('V', 'Vaccum Sealed')], default='Box', max_length=100)),
                ('product_photo', models.ImageField(upload_to='photos/')),
                ('delivery', models.CharField(choices=[('Yes', 'yes'), ('No', 'No')], default='Yes', max_length=4)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.foodsshopseller')),
            ],
        ),
        migrations.CreateModel(
            name='FruitsProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_photo', models.ImageField(upload_to='photos/')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('delivery', models.CharField(choices=[('Yes', 'yes'), ('No', 'No')], max_length=4)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.fruitsshopseller')),
            ],
        ),
        migrations.CreateModel(
            name='GroceryProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_photo', models.ImageField(upload_to='photos/')),
                ('delivery', models.CharField(choices=[('Yes', 'yes'), ('N', 'No')], default='Yes', max_length=4)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.groceryshopseller')),
            ],
        ),
        migrations.CreateModel(
            name='HouseComponentProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_photo', models.ImageField(upload_to='photos/')),
                ('Size', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=50)),
                ('product_description', models.TextField(max_length=200)),
                ('delivery', models.CharField(choices=[('Yes', 'yes'), ('No', 'No')], default='Yes', max_length=4)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.housecomponentshopseller')),
            ],
        ),
        migrations.CreateModel(
            name='IceCreamProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flavor', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=20)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='ice_cream_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('delivery', models.CharField(choices=[('Yes', 'yes'), ('No', 'No')], default='Yes', max_length=4)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.icecreamshopseller')),
            ],
        ),
        migrations.CreateModel(
            name='MeatProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('beef', 'Beef'), ('chicken', 'Chicken'), ('pork', 'Pork'), ('lamb', 'Lamb')], max_length=50)),
                ('weight', models.FloatField()),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='meat_images/')),
                ('delivery', models.CharField(choices=[('Yes', 'yes'), ('No', 'No')], default='Yes', max_length=4)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.meatshopseller')),
            ],
        ),
        migrations.CreateModel(
            name='VegetablesProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('quantity_available', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='vegetable_images/')),
                ('delivery', models.CharField(choices=[('Yes', 'yes'), ('No', 'No')], default='Yes', max_length=4)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.vegetablesshopseller')),
            ],
        ),
    ]
