# Generated by Django 5.1.3 on 2024-11-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothesproducts',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='drinksproducts',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='electronicsproducts',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='foodsproducts',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='fruitsproducts',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='groceryproducts',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='housecomponentproducts',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='icecreamproducts',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='meatproducts',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='vegetablesproducts',
            name='seller',
        ),
    ]
