# Generated by Django 5.1.3 on 2024-11-19 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_clothesproducts_seller_and_more'),
        ('seller', '0002_remove_clothesshopseller_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothesproducts',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.clothesshopseller'),
        ),
        migrations.AddField(
            model_name='drinksproducts',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.drinksshopseller'),
        ),
        migrations.AddField(
            model_name='electronicsproducts',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.electronicsshopseller'),
        ),
        migrations.AddField(
            model_name='foodsproducts',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.foodsshopseller'),
        ),
        migrations.AddField(
            model_name='fruitsproducts',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.fruitsshopseller'),
        ),
        migrations.AddField(
            model_name='groceryproducts',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.groceryshopseller'),
        ),
        migrations.AddField(
            model_name='housecomponentproducts',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.housecomponentshopseller'),
        ),
        migrations.AddField(
            model_name='icecreamproducts',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.icecreamshopseller'),
        ),
        migrations.AddField(
            model_name='meatproducts',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.meatshopseller'),
        ),
        migrations.AddField(
            model_name='vegetablesproducts',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.vegetablesshopseller'),
        ),
    ]
