# Generated by Django 5.1.3 on 2024-11-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_meatproducts_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meatproducts',
            name='price_per_kg',
        ),
        migrations.RemoveField(
            model_name='vegetablesproducts',
            name='price_per_unit',
        ),
    ]
