# Generated by Django 5.1.3 on 2024-11-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_meatproducts_price_per_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meatproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
        ),
        migrations.AddField(
            model_name='vegetablesproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=7),
        ),
        migrations.AlterField(
            model_name='clothesproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
        ),
    ]
